### ISSUE TITLE
remove dummy provider class to avoid duplicate rows in the table

### ISSUE THREAD

**Issue by MariamnaKh** [Oleksandr-Eleks/pharmagator#33]
load data method of dummy provider class creates duplicate values, which leads to an error while updating medicine

**Comment by MuchosChuchos** [comment]
I have done it by adding @Profile, so we can not remove it from our codebase.

**Comment by Oleksandr-Eleks** [comment]
Nice, but let's remove it anyway. :)

**Comment by MariamnaKh** [comment]
I think that it makes no sense for us to keep this implementation as it only generates random values

**Comment by MuchosChuchos** [comment]
Merged
