### ISSUE TITLE
Fix create method in PriceController and PriceService

### ISSUE THREAD

**Issue by MariamnaKh** [Oleksandr-Eleks/pharmagator#64]
remove create/save method from PriceController and PriceService as it should be only updated

**Comment by Oleksandr-Eleks** [comment]
@MariamnaKh could You please elaborate a bit more here?

**Comment by MariamnaKh** [comment]
added short description

**Comment by Oleksandr-Eleks** [comment]
Having new price for specific Pharmacy and Medicine means that we should already have existing one. And here, existing price should be updated only, if to talk in perspective of external API. Isn't it?
