### ISSUE TITLE
Wrong usage of http headers in MedecineControllerTest

### ISSUE THREAD

**Issue by MuchosChuchos** [Oleksandr-Eleks/pharmagator#91]
Difference between "accept" and "content-type"

**Comment by MariamnaKh** [comment]
@MuchosChuchos try to explain yourself clearly. I agree with contentType in some cases, but what do you wanna say with this description? you wanna add accept in some tests? and if yes, what do you think we will verify?

**Comment by MuchosChuchos** [comment]
@MariamnaKh, I mean you should check that diff and then the usage of these headers in your code.
